// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGCWG-3CD1VhGBZAwGhfwZ1l76BCAQROs',
    appId: '1:779119837127:web:52628dbab39aa1e11be3e2',
    messagingSenderId: '779119837127',
    projectId: 'smart-kids-b76c1',
    authDomain: 'smart-kids-b76c1.firebaseapp.com',
    storageBucket: 'smart-kids-b76c1.firebasestorage.app',
    measurementId: 'G-L4YC7CCBP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG7JA302MlbkwhaV1rBEwdIqo8XPKqGGc',
    appId: '1:779119837127:android:eea3934ebd926df21be3e2',
    messagingSenderId: '779119837127',
    projectId: 'smart-kids-b76c1',
    storageBucket: 'smart-kids-b76c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLq22wpyzpQhh86So9YQWbLP4ZPNUPg9A',
    appId: '1:779119837127:ios:afa09f0c780def0d1be3e2',
    messagingSenderId: '779119837127',
    projectId: 'smart-kids-b76c1',
    storageBucket: 'smart-kids-b76c1.firebasestorage.app',
    iosBundleId: 'com.smartmetrics.smartkids',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLq22wpyzpQhh86So9YQWbLP4ZPNUPg9A',
    appId: '1:779119837127:ios:afa09f0c780def0d1be3e2',
    messagingSenderId: '779119837127',
    projectId: 'smart-kids-b76c1',
    storageBucket: 'smart-kids-b76c1.firebasestorage.app',
    iosBundleId: 'com.smartmetrics.smartkids',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGCWG-3CD1VhGBZAwGhfwZ1l76BCAQROs',
    appId: '1:779119837127:web:43842373873f17291be3e2',
    messagingSenderId: '779119837127',
    projectId: 'smart-kids-b76c1',
    authDomain: 'smart-kids-b76c1.firebaseapp.com',
    storageBucket: 'smart-kids-b76c1.firebasestorage.app',
    measurementId: 'G-BSX9GHWR5B',
  );
}
